#!/bin/sh
# shellcheck disable=SC2015

#    This file is part of Glorious-Dotfiles.
#
#    Glorious-Dotfiles is free software: you can redistribute it and/or modify it under
#    the terms of the GNU General Public License as published by the
#    Free Software Foundation, either version 3 of the License, or (at your
#    option) any later version.
#
#    Glorious-Dotfiles is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see https://www.gnu.org/licenses/.

# Set environment variables to default when they are not set
[ -z "$DOTS_DIR" ] && DOTS_DIR="$HOME/git-src/glorious-dotfiles"

# Command: $ dotsmgr push
#push() {
#}

# Command: $ dotsmgr pull
# Pull the latest release of my dotfiles
pull() {
	printf "Pulling the latest release...\n"
	git pull && (printf "Done!\n" && exit 0) || (printf "Oops! Something wrong happened!\n" && exit 1)
}

# Command: $ dotsmgr dwm
# Installs my dwm build
dwm() {
	printf "Cloning the repository...\n"
	git clone https://github.com/neo64yt/dwm-neo64.git ../dwm-neo64
	printf "Installing dwm to your system...\n"
	../dwm-neo64/install.sh && (printf "Installation finished!\n" && exit 0) || (printf "Oops! Something wrong happened!\n" && exit 1)
}



# Command: $ dotsmgr help
help() {
	cat << EOF
dotsmgr

Never run this script as root!

Usage: 
	dotsmgr [COMMAND]
	[ENVIRONMENT VARIABLES..] dotsmgr [COMMAND]

Commands:
	pull:		Pulls the latest release of my dotfiles
	dwm:		Installs my dwm build	
	help: 		Shows usage, commands and environment variables
	about:		Shows information about this script 

Environment variables:
	DOTS_DIR (string):		The directory of the dotfiles repository.
		Default: $HOME/git-src/glorious-dotfiles
EOF
}

# Command: $ dotsmgr about
# About this script
about() {
	cat << EOF
About dotsmgr:
	Author: Neo64YT (https://github.com/neo64yt)
	Git repository: https://github.com/neo64yt/glorious-dotfiles
	Description: A script for managing dotfiles, included in glorious-dotfiles. Mainly using stow to have a neat and clean dotfiles management
EOF
}

# Read functions as commands. Function "help" executed when there is no command / the command used is not supported
[ -n "$1" ] && $1 || (help && exit 1)



# vim: ft=sh
