#!/bin/sh

#      █████  ██      ██  █████  ███████ ██████   ██████ 
#     ██   ██ ██      ██ ██   ██ ██      ██   ██ ██      
#     ███████ ██      ██ ███████ ███████ ██████  ██      
#     ██   ██ ██      ██ ██   ██      ██ ██   ██ ██      
#     ██   ██ ███████ ██ ██   ██ ███████ ██   ██  ██████
#
#                 pyromorphic-desktop

alias rm="rm -rI" # Ask before deleting files recursively
alias ls="ls -A --color=auto" # List all files including hidden ones
alias grep="grep -i" # Grep
alias clean-cache="rm -rf $XDG_CACHE_HOME/*" # Clean home directory cache
alias cp="cp -r" # Copy files
alias ..="cd .." # Go to parent directory 
alias desktop="desktop-file-validate" # Validating .desktop files
alias patch-del="patch -R" # Reversing patches
alias vim="nvim" # Assume Neovim as Vim
alias commit="git commit" # Commiting Git changes
alias push="git push" # Push Git commits to upstream repository
alias pull="git pull" # Sync local Git repository with upstream
alias :x="exit" # Vim-like exit :P
alias musicdl="yt-dlp -x -f bestaudio/best --extract-audio --audio-format opus --audio-quality 0"
alias swallow="devour"



# vim: ft=sh
