#!/bin/zsh

# This file stores environment variables 

## GENERIC CONFIGURATION ##
export PATH="${HOME}/.local/bin:${PATH}" # Binaries path
export XDG_CONFIG_HOME="${HOME}/.config" # XDG configuration directory (user)
export XDG_DATA_HOME="${HOME}/.local/share" # XDG data directory (user)
export XDG_CACHE_HOME="${HOME}/.cache" # XDG cache directory (user)
export XDG_STATE_HOME="${HOME}/.local/state" # XDG state directory (user)
export HISTFILE="${XDG_STATE_HOME}/shell/zsh_history" # History file for zsh
export COMPDUMPFILE="${XDG_CACHE_HOME}/zsh/zcompdump" # zcompdump
export KEYBIND="${XDG_CONFIG_HOME}/sxhkd/sxhkdrc" # WM-independent keybindings
export AUTOSTART="${XDG_CONFIG_HOME}/autostart-cmds/autostart.sh" # WM-independent autostart
export PAGER="nvimpager" # Use more as pager
export MANPAGER="${PAGER}" # Use Neovim as manpager
export GNUPGHOME="${XDG_DATA_HOME}/gnupg" # GnuPG directory
export VISUAL="nvim"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/shell/starship.toml"
export COWPATH="${XDG_DATA_HOME}/cows:/usr/share/cows"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc" # Wget config file location
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"

## SCRIPTS ##
export QUICKMENU="quickmenu"
export SETTINGS_MGR="set-mgr"
export SESSION_MGR="sessionmgr"
export EMOJI_PICKER="dmenuemoji"
export LOCK="lock" 
export SCREENSHOOTER="screenshot"

## SESSION ##
export DE="xfce"
export DESKTOP_SESSION="${DE}"
export XDG_DESKTOP_SESSION="${DE}"
export $(dbus-launch)

## DMENU DEFAULT LOOK ##
export DMENU_HEIGHT="35"
export DMENU_LINES="15"
export DMENU_BORDER="3"

## DEFAULT PROGRAMS ##
export TERMINAL="alacritty"
export EDITOR="nvim"
export BROWSER="firefox"
export LOCKER="xsecurelock"

## SETTINGS MANAGER ##
export SET_GENERAL="xfce4-settings-manager" # General settings
export QT5_SETTINGS="qt5ct" # Appearance (Qt5)
export POWER_MGR="mate-power-preferences" # Power manager
export NM_EDITOR="nm-connection-editor" # Network
export PRINT="system-config-printer" # Printer
export BACKUP_UTIL="timeshift-launcher" # Backup & restore utility
export DCONF_EDITOR="dconf-editor" # Manage Dconf configurations

## XSECURELOCK SETTINGS ##
export XSECURELOCK_PASSWORD_PROMPT="asterisks"
export XSECURELOCK_FONT="JetBrains Mono:size=15"
export XSECURELOCK_COMPOSITE_OBSCURER="0"
export XSECURELOCK_SHOW_DATETIME="1"
export XSECURELOCK_SHOW_HOSTNAME="2"
export XSECURELOCK_AUTH_CURSOR_BLINK="1"
export XSECURELOCK_AUTH_SOUNDS="1"

## SCREENREC SETTINGS ##
export SCREENREC_INRES="1366x768"
export SCREENREC_SCALE="1280x720"
export SCREENREC_SCALEFLAGS="lanczos"
export SCREENREC_FPS="30"
export SCREENREC_AUDIO="pulse"
export SCREENREC_VCODEC="libx264"
export SCREENREC_PRESET="ultrafast"
export SCREENREC_ACODEC="libmp3lame"
export SCREENREC_THREADS="0"



# vim: ft=zsh
## EOF ##
