#!/bin/zsh
#   |\     |
#   | \    |
#   |  \   |
#   |   \  |
#   |    \ |
#   |     \|
# (c) Made by Neo64YT

# Dump 
mkdir -p $XDG_CACHE_HOME/zsh

# Show fetch tool
pfetch

# Hello message
hello | cowsay -f tux -n | lolcat

# Aliases
source $XDG_CONFIG_HOME/shell/aliasrc # Sourced from $XDG_CONFIG_HOME/shell/aliasrc

# Environment variables
# All environment variables are stored in .zprofile and .xprofile (both are symlinks to $XDG_CONFIG_HOME/shell/envrc) 

# Plugins 
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh # Syntax highlighting
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh # Autosuggestions

# Functions

## START ##

## Commands cheatsheet
cheat(){
	curl https://cheat.sh/${@};
}

## Removing an XDG autostart app
undex(){
	touch $XDG_CONFIG_HOME/autostart/${@}.desktop && printf "\"${@}\" was successfully removed from the autostart list.\n"
}

## Re-adding an XDG autostart app
redex(){
	rm -rf $XDG_CONFIG_HOME/autostart/${@}.desktop 2>/dev/null && printf "\"${@}\" was successfully re-added to the autostart list.\n" || printf "\"${@}\" isn't in the removed autostart list.\n"
}

## END ##

# Starship prompt
prompt off  # Disable prompt theme engine
eval "$(starship init zsh)"



# vim: ft=zsh
## EOF ##
