[colors]
background = #000000
foreground = #ffffff
primary = #12846e
ws-bg-active = #272a34
alert = #A54242
volume = #1075e8
bat-charge = #2a9c5f
bat-norm = #0fbdd1
bat-low = #ed0c1f
cpu = #ede20c
ram = #a718db
date = #c77810
music = #85e21b 


[bar/main]
width = 100%
height = 50px

dpi = 192

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 4px

padding-left = 0
padding-right = 1

module-margin = 1

font-0 = JetBrains Mono:size=11
font-1 = Material Design Icons:size=11;1
font-2 = Mada:size=11

modules-left = xworkspaces xwindow
modules-right = music volume battery cpu memory date ewwtray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

icon-0 = one;󰋜
icon-1 = two;󰺶
icon-2 = three;󰆍
icon-3 = four;󰆌
icon-4 = five;󰐋
icon-5 = six;󰠔

label-active = %icon%
label-active-background = ${colors.ws-bg-active}
label-active-foreground = ${colors.primary}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %icon%
label-occupied-foreground= ${colors.foreground}
label-occupied-underline= ${colors.foreground}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-padding = 0

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/music]
type = internal/mpd
host = localhost
port = 6600

format-online = <label-song>
label-song = 󰎇 %title%

[module/volume]
type = custom/ipc
label-foreground = ${colors.volume}
label = %output%

hook-0 = /usr/local/bin/wp_vol
initial = 1
click-left = volumectl mute
scroll-down = volumectl up 
scroll-up = volumectl down

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.ram}
label-foreground = ${colors.ram}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰘚 "
format-prefix-foreground = ${colors.cpu}
label-foreground = ${colors.cpu}
label = %percentage:2%%

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1

format-charging-foreground = ${colors.bat-charge}
format-discharging-foreground = ${colors.bat-norm}
format-low-foreground = ${colors.bat-low}
format-full-foreground = ${colors.bat-norm}

format-charging = <animation-charging><label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-low = <ramp-capacity><animation-low> <label-low>  
format-full = <ramp-capacity> <label-full>
label-charging = 󰉁 %percentage%%
label-discharging = %percentage%%
label-low = %percentage%%
label-full = %percentage%%

ramp-capacity-0 = 󰂎 
ramp-capacity-1 = 󰁼 
ramp-capacity-2 = 󰁾 
ramp-capacity-3 = 󰂀 
ramp-capacity-4 = 󰁹

animation-charging-framerate = 750

animation-charging-0 = 󰂎 
animation-charging-1 = 󰁼 
animation-charging-2 = 󰁾 
animation-charging-3 = 󰂀 
animation-charging-4 = 󰁹

animation-low-0 = 󱈸
animation-low-1 = 
animation-low-framerate = 200

[module/date]
type = internal/date
interval = 1

date = 󰅐 %H:%M
date-alt = 󰸗 %a, %d/%m

label = %date%
label-foreground = ${colors.date}

[module/ewwtray]
type = custom/text

label = 󱨇
click-left = eww open tray --toggle
padding-right = 0

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
