#!/bin/sh

# Defaults
prompt="Something random:"
BEMENU_OPTS="$BEMENU_OPTS -p '$prompt'"

# List of choices
list_choices(){
	cat << EOF
Just
as
an
example
EOF
}

# Command
choice=$(list_choices | bemenu)

case "$choice" in
  	"Just") ok ;;
  	"as") ok ;;
  	"an") OK ;;
  	"example") OK ;;
	*) exit 1 ;;
esac



# vim: ft=sh
