#!/bin/sh

# Scripts directory

# Defaults
lines="$DMENU_LINES"
border="$DMENU_BORDER"
height="$DMENU_HEIGHT"
prompt="Somthing random:"

# List of choices
list_choices(){
	cat << EOF
Just
as
an
example
EOF
}

# dmenu command
dmenu_cmd(){
	dmenu -c -n -l $lines -bw $border -h $height -p "$prompt"
}

# Command
choice=$(list_choices | dmenu_cmd)

case "$choice" in
  	"Just") ok ;;
  	"as") ok ;;
  	"an") OK ;;
  	"example") OK ;;
esac



# vim: ft=sh
