#!/bin/sh

export WM_CONFIG_DIR="${XDG_CONFIG_HOME}/dwm"
export SESSION_QUIT="$WM_CONFIG_DIR/dwmmgr quit"
export SESSION_REFRESH="$WM_CONFIG_DIR/dwmmgr restart"
export WM_AUTOSTART="${WM_CONFIG_DIR}/autostart.sh"
export WM_KEYBIND="${WM_CONFIG_DIR}/NOTE"



# vim: ft=sh
